from django.urls import path
from .views import (
    AdminBrowseUserView,
    AdminBrowseUnverifiedUserView,
    MyUserView,
    UsersListView,
    UsersUnverifiedListView,
    VerifiyUserView,
    DeleteUserView,
    ToggleUserRoleView,
    RegisterUserView,
    BlacklistedUsersListView,
    UnbanUserView,
    PasswordUpdateView,
)

urlpatterns = [
    path(
        "me/",
        MyUserView.as_view(),
        name="user-me",
    ),
    path(
        "me/update/password/",
        PasswordUpdateView.as_view(),
        name="user-update-password",
    ),
    path(
        "list/",
        UsersListView.as_view(),
        name="user-list",
    ),
    path(
        "list/unverified/",
        UsersUnverifiedListView.as_view(),
        name="user-list-unverified",
    ),
    path(
        "list/blacklisted/",
        BlacklistedUsersListView.as_view(),
        name="user-list-blacklisted",
    ),
    path(
        "<int:user_id>/",
        AdminBrowseUserView.as_view(),
        name="user-detail",
    ),
    path(
        "unverified/<int:user_id>/",
        AdminBrowseUnverifiedUserView.as_view(),
        name="user-detail-unverified",
    ),
    path(
        "verify/<int:user_id>/",
        VerifiyUserView.as_view(),
        name="user-verify",
    ),
    path(
        "unban/<int:blacklist_id>/",
        UnbanUserView.as_view(),
        name="user-unban",
    ),
    path(
        "toggle-role/<int:user_id>/",
        ToggleUserRoleView.as_view(),
        name="user-toggle-role",
    ),
    path(
        "register/",
        RegisterUserView.as_view(),
        name="user-register",
    ),
    path(
        "delete/<int:user_id>/",
        DeleteUserView.as_view(),
        name="user-delete",
    ),
]
